SEMANTIC_TAGS = [
    "body structure",
    "cell",
    "cell structure",
    "morphologic abnormality",
    "finding",
    "disorder",
    "environment",
    "geographic location",
    "event",
    "observable entity",
    "organism",
    "clinical drug",
    "medicinal product",
    "medicinal product form",
    "physical object",
    "product",
    "physical force",
    "procedure",
    "regime/therapy",
    "qualifier value",
    "administration method",
    "basic dose form",
    "disposition",
    "dose form",
    "intended site",
    "number",
    "product name",
    "release characteristic",
    "role",
    "state of matter",
    "transformation",
    "supplier",
    "unit of presentation",
    "record artifact",
    "situation",
    "attribute",
    "core metadata concept",
    "foundation metadata concept",
    "link assertion",
    "linkage concept",
    "namespace concept",
    "OWL metadata concept",
    "social concept",
    "ethnic group",
    "life style",
    "occupation",
    "person",
    "racial group",
    "religion/philosophy",
    "inactive concept",
    "navigational concept",
    "specimen",
    "staging scale",
    "assessment scale",
    "tumor staging",
    "substance",
]
